name: 'Setup kafka with config'
description: 'Additional configuration file for kafka instance'
author: 'blint96'
inputs:
  kafka_version:
    description: 'Version of Kafka to use'
    required: false
    default: 'latest'
  zookeeper_version:
    description: 'Version of Zookeeper to use'
    required: false
    default: 'latest'    
  kafka_port:
    description: 'The port of Kafka host'
    required: false
    default: 9092
  zookeeper_port:
    description: 'The port of Zookeeper host'
    required: false
    default: 2181    
runs:
  using: 'docker'
  image: 'Dockerfile'